# Generated by Django 5.2.8 on 2025-11-25 05:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField()),
                ('original_text', models.TextField()),
                ('translated_text', models.TextField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='api.document')),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
    ]
