# Generated by Django 5.2.8 on 2025-11-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_quiz_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='processing_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
