# Generated by Django 5.2.8 on 2025-12-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_message_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('MULTIPLE_CHOICE', 'Multiple Choice'), ('FLASHCARD', 'Flashcard')], default='MULTIPLE_CHOICE', max_length=20),
        ),
    ]
